import type { Metadata } from "next";
import {  Manrope, Poppins } from "next/font/google";
import "./globals.css";
import { ChildProps } from "./types";


const poppins=Poppins({
  weight:['400','500','600'],
  subsets:["latin"],
  variable:'--font-poppins'
})


const manrope=Manrope({
  weight:['600'],
  subsets:["latin"],
  variable:'--font-manrope'
})
// Poppins 400  500 600 Manrope 600
export const metadata: Metadata = {
  title: "Finsweet",
  description: "Generated by create next app",
};

export default function RootLayout({children}: ChildProps) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${manrope.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
